/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param authenticator 
 * @param authenticatorConfig 
 * @param authenticatorFlow 
 * @param flowId 
 * @param id 
 * @param parentFlow 
 * @param priority 
 * @param requirement 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class AuthenticationExecutionRepresentation (
    val authenticator: kotlin.String? = null,
    val authenticatorConfig: kotlin.String? = null,
    val authenticatorFlow: kotlin.Boolean? = null,
    val flowId: kotlin.String? = null,
    val id: kotlin.String? = null,
    val parentFlow: kotlin.String? = null,
    val priority: kotlin.Int? = null,
    val requirement: kotlin.String? = null
) {

}

