/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param alias 
 * @param authenticationConfig 
 * @param authenticationFlow 
 * @param configurable 
 * @param description 
 * @param displayName 
 * @param flowId 
 * @param id 
 * @param index 
 * @param level 
 * @param providerId 
 * @param requirement 
 * @param requirementChoices 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class AuthenticationExecutionInfoRepresentation (
    val alias: kotlin.String? = null,
    val authenticationConfig: kotlin.String? = null,
    val authenticationFlow: kotlin.Boolean? = null,
    val configurable: kotlin.Boolean? = null,
    val description: kotlin.String? = null,
    val displayName: kotlin.String? = null,
    val flowId: kotlin.String? = null,
    val id: kotlin.String? = null,
    val index: kotlin.Int? = null,
    val level: kotlin.Int? = null,
    val providerId: kotlin.String? = null,
    val requirement: kotlin.String? = null,
    val requirementChoices: kotlin.Array<kotlin.String>? = null
) {

}

