/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.AuthenticationExecutionExportRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param alias 
 * @param authenticationExecutions 
 * @param builtIn 
 * @param description 
 * @param id 
 * @param providerId 
 * @param topLevel 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class AuthenticationFlowRepresentation (
    val alias: kotlin.String? = null,
    val authenticationExecutions: kotlin.Array<AuthenticationExecutionExportRepresentation>? = null,
    val builtIn: kotlin.Boolean? = null,
    val description: kotlin.String? = null,
    val id: kotlin.String? = null,
    val providerId: kotlin.String? = null,
    val topLevel: kotlin.Boolean? = null
) {

}

