/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.ClientPolicyConditionRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param conditions 
 * @param description 
 * @param enabled 
 * @param name 
 * @param profiles 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ClientPolicyRepresentation (
    val conditions: kotlin.Array<ClientPolicyConditionRepresentation>? = null,
    val description: kotlin.String? = null,
    val enabled: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val profiles: kotlin.Array<kotlin.String>? = null
) {

}

