/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.ProtocolMapperRepresentation
import fi.metatavu.keycloak.adminclient.models.ResourceServerRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param access 
 * @param adminUrl 
 * @param alwaysDisplayInConsole 
 * @param attributes 
 * @param authenticationFlowBindingOverrides 
 * @param authorizationServicesEnabled 
 * @param authorizationSettings 
 * @param baseUrl 
 * @param bearerOnly 
 * @param clientAuthenticatorType 
 * @param clientId 
 * @param consentRequired 
 * @param defaultClientScopes 
 * @param description 
 * @param directAccessGrantsEnabled 
 * @param enabled 
 * @param frontchannelLogout 
 * @param fullScopeAllowed 
 * @param id 
 * @param implicitFlowEnabled 
 * @param name 
 * @param nodeReRegistrationTimeout 
 * @param notBefore 
 * @param oauth2DeviceAuthorizationGrantEnabled 
 * @param optionalClientScopes 
 * @param origin 
 * @param protocol 
 * @param protocolMappers 
 * @param publicClient 
 * @param redirectUris 
 * @param registeredNodes 
 * @param registrationAccessToken 
 * @param rootUrl 
 * @param secret 
 * @param serviceAccountsEnabled 
 * @param standardFlowEnabled 
 * @param surrogateAuthRequired 
 * @param webOrigins 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ClientRepresentation (
    val access: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val adminUrl: kotlin.String? = null,
    val alwaysDisplayInConsole: kotlin.Boolean? = null,
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val authenticationFlowBindingOverrides: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val authorizationServicesEnabled: kotlin.Boolean? = null,
    val authorizationSettings: ResourceServerRepresentation? = null,
    val baseUrl: kotlin.String? = null,
    val bearerOnly: kotlin.Boolean? = null,
    val clientAuthenticatorType: kotlin.String? = null,
    val clientId: kotlin.String? = null,
    val consentRequired: kotlin.Boolean? = null,
    val defaultClientScopes: kotlin.Array<kotlin.String>? = null,
    val description: kotlin.String? = null,
    val directAccessGrantsEnabled: kotlin.Boolean? = null,
    val enabled: kotlin.Boolean? = null,
    val frontchannelLogout: kotlin.Boolean? = null,
    val fullScopeAllowed: kotlin.Boolean? = null,
    val id: kotlin.String? = null,
    val implicitFlowEnabled: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val nodeReRegistrationTimeout: kotlin.Int? = null,
    val notBefore: kotlin.Int? = null,
    val oauth2DeviceAuthorizationGrantEnabled: kotlin.Boolean? = null,
    val optionalClientScopes: kotlin.Array<kotlin.String>? = null,
    val origin: kotlin.String? = null,
    val protocol: kotlin.String? = null,
    val protocolMappers: kotlin.Array<ProtocolMapperRepresentation>? = null,
    val publicClient: kotlin.Boolean? = null,
    val redirectUris: kotlin.Array<kotlin.String>? = null,
    val registeredNodes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val registrationAccessToken: kotlin.String? = null,
    val rootUrl: kotlin.String? = null,
    val secret: kotlin.String? = null,
    val serviceAccountsEnabled: kotlin.Boolean? = null,
    val standardFlowEnabled: kotlin.Boolean? = null,
    val surrogateAuthRequired: kotlin.Boolean? = null,
    val webOrigins: kotlin.Array<kotlin.String>? = null
) {

}

