/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param containerId 
 * @param containerName 
 * @param containerType 
 * @param mapperId 
 * @param mapperName 
 * @param protocolMapper 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ClientScopeEvaluateResourceMinusProtocolMapperEvaluationRepresentation (
    val containerId: kotlin.String? = null,
    val containerName: kotlin.String? = null,
    val containerType: kotlin.String? = null,
    val mapperId: kotlin.String? = null,
    val mapperName: kotlin.String? = null,
    val protocolMapper: kotlin.String? = null
) {

}

