/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param count 
 * @param expiration 
 * @param id 
 * @param remainingCount 
 * @param timestamp 
 * @param token 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ClientInitialAccessPresentation (
    val count: kotlin.Int? = null,
    val expiration: kotlin.Int? = null,
    val id: kotlin.String? = null,
    val remainingCount: kotlin.Int? = null,
    val timestamp: kotlin.Int? = null,
    val token: kotlin.String? = null
) {

}

