/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.MultivaluedHashMap

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param config 
 * @param id 
 * @param name 
 * @param parentId 
 * @param providerId 
 * @param providerType 
 * @param subType 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ComponentRepresentation (
    val config: MultivaluedHashMap? = null,
    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val parentId: kotlin.String? = null,
    val providerId: kotlin.String? = null,
    val providerType: kotlin.String? = null,
    val subType: kotlin.String? = null
) {

}

