/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param defaultValue 
 * @param helpText 
 * @param label 
 * @param name 
 * @param options 
 * @param secret 
 * @param type 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class ConfigPropertyRepresentation (
    val defaultValue: kotlin.Any? = null,
    val helpText: kotlin.String? = null,
    val label: kotlin.String? = null,
    val name: kotlin.String? = null,
    val options: kotlin.Array<kotlin.String>? = null,
    val secret: kotlin.Boolean? = null,
    val type: kotlin.String? = null
) {

}

