/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param createdDate 
 * @param credentialData 
 * @param id 
 * @param priority 
 * @param secretData 
 * @param temporary 
 * @param type 
 * @param userLabel 
 * @param &#x60;value&#x60; 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class CredentialRepresentation (
    val createdDate: kotlin.Long? = null,
    val credentialData: kotlin.String? = null,
    val id: kotlin.String? = null,
    val priority: kotlin.Int? = null,
    val secretData: kotlin.String? = null,
    val temporary: kotlin.Boolean? = null,
    val type: kotlin.String? = null,
    val userLabel: kotlin.String? = null,
    val `value`: kotlin.String? = null
) {

}

