/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param access 
 * @param attributes 
 * @param clientRoles 
 * @param id 
 * @param name 
 * @param path 
 * @param realmRoles 
 * @param subGroups 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class GroupRepresentation (
    val access: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val clientRoles: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val id: kotlin.String? = null,
    val name: kotlin.String? = null,
    val path: kotlin.String? = null,
    val realmRoles: kotlin.Array<kotlin.String>? = null,
    val subGroups: kotlin.Array<GroupRepresentation>? = null
) {

}

