/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param addReadTokenRoleOnCreate 
 * @param alias 
 * @param config 
 * @param displayName 
 * @param enabled 
 * @param firstBrokerLoginFlowAlias 
 * @param internalId 
 * @param linkOnly 
 * @param postBrokerLoginFlowAlias 
 * @param providerId 
 * @param storeToken 
 * @param trustEmail 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class IdentityProviderRepresentation (
    val addReadTokenRoleOnCreate: kotlin.Boolean? = null,
    val alias: kotlin.String? = null,
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val displayName: kotlin.String? = null,
    val enabled: kotlin.Boolean? = null,
    val firstBrokerLoginFlowAlias: kotlin.String? = null,
    val internalId: kotlin.String? = null,
    val linkOnly: kotlin.Boolean? = null,
    val postBrokerLoginFlowAlias: kotlin.String? = null,
    val providerId: kotlin.String? = null,
    val storeToken: kotlin.Boolean? = null,
    val trustEmail: kotlin.Boolean? = null
) {

}

