/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.AddressClaimSet

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param acr 
 * @param address 
 * @param atHash 
 * @param authTime 
 * @param azp 
 * @param birthdate 
 * @param cHash 
 * @param category 
 * @param claimsLocales 
 * @param email 
 * @param emailVerified 
 * @param exp 
 * @param familyName 
 * @param gender 
 * @param givenName 
 * @param iat 
 * @param iss 
 * @param jti 
 * @param locale 
 * @param middleName 
 * @param name 
 * @param nbf 
 * @param nickname 
 * @param nonce 
 * @param otherClaims 
 * @param phoneNumber 
 * @param phoneNumberVerified 
 * @param picture 
 * @param preferredUsername 
 * @param profile 
 * @param sHash 
 * @param sessionState 
 * @param sub 
 * @param typ 
 * @param updatedAt 
 * @param website 
 * @param zoneinfo 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class IDToken (
    val acr: kotlin.String? = null,
    val address: AddressClaimSet? = null,
    val atHash: kotlin.String? = null,
    val authTime: kotlin.Long? = null,
    val azp: kotlin.String? = null,
    val birthdate: kotlin.String? = null,
    val cHash: kotlin.String? = null,
    val category: IDToken.Category? = null,
    val claimsLocales: kotlin.String? = null,
    val email: kotlin.String? = null,
    val emailVerified: kotlin.Boolean? = null,
    val exp: kotlin.Long? = null,
    val familyName: kotlin.String? = null,
    val gender: kotlin.String? = null,
    val givenName: kotlin.String? = null,
    val iat: kotlin.Long? = null,
    val iss: kotlin.String? = null,
    val jti: kotlin.String? = null,
    val locale: kotlin.String? = null,
    val middleName: kotlin.String? = null,
    val name: kotlin.String? = null,
    val nbf: kotlin.Long? = null,
    val nickname: kotlin.String? = null,
    val nonce: kotlin.String? = null,
    val otherClaims: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val phoneNumber: kotlin.String? = null,
    val phoneNumberVerified: kotlin.Boolean? = null,
    val picture: kotlin.String? = null,
    val preferredUsername: kotlin.String? = null,
    val profile: kotlin.String? = null,
    val sHash: kotlin.String? = null,
    val sessionState: kotlin.String? = null,
    val sub: kotlin.String? = null,
    val typ: kotlin.String? = null,
    val updatedAt: kotlin.Long? = null,
    val website: kotlin.String? = null,
    val zoneinfo: kotlin.String? = null
) {

    /**
    * 
    * Values: iNTERNAL,aCCESS,iD,aDMIN,uSERINFO,lOGOUT
    */
    enum class Category(val value: kotlin.String){
    
        iNTERNAL("INTERNAL"),
    
        aCCESS("ACCESS"),
    
        iD("ID"),
    
        aDMIN("ADMIN"),
    
        uSERINFO("USERINFO"),
    
        lOGOUT("LOGOUT");
    
    }

}

