/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param array 
 * @param bigDecimal 
 * @param bigInteger 
 * @param binary 
 * @param boolean 
 * @param containerNode 
 * @param double 
 * @param empty 
 * @param float 
 * @param floatingPointNumber 
 * @param int 
 * @param integralNumber 
 * @param long 
 * @param missingNode 
 * @param nodeType 
 * @param &#x60;null&#x60; 
 * @param number 
 * @param &#x60;object&#x60; 
 * @param pojo 
 * @param short 
 * @param textual 
 * @param valueNode 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class JsonNode (
    val array: kotlin.Boolean? = null,
    val bigDecimal: kotlin.Boolean? = null,
    val bigInteger: kotlin.Boolean? = null,
    val binary: kotlin.Boolean? = null,
    val boolean: kotlin.Boolean? = null,
    val containerNode: kotlin.Boolean? = null,
    val double: kotlin.Boolean? = null,
    val empty: kotlin.Boolean? = null,
    val float: kotlin.Boolean? = null,
    val floatingPointNumber: kotlin.Boolean? = null,
    val int: kotlin.Boolean? = null,
    val integralNumber: kotlin.Boolean? = null,
    val long: kotlin.Boolean? = null,
    val missingNode: kotlin.Boolean? = null,
    val nodeType: JsonNode.NodeType? = null,
    val `null`: kotlin.Boolean? = null,
    val number: kotlin.Boolean? = null,
    val `object`: kotlin.Boolean? = null,
    val pojo: kotlin.Boolean? = null,
    val short: kotlin.Boolean? = null,
    val textual: kotlin.Boolean? = null,
    val valueNode: kotlin.Boolean? = null
) {

    /**
    * 
    * Values: aRRAY,bINARY,bOOLEAN,mISSING,nULL,nUMBER,oBJECT,pOJO,sTRING
    */
    enum class NodeType(val value: kotlin.String){
    
        aRRAY("ARRAY"),
    
        bINARY("BINARY"),
    
        bOOLEAN("BOOLEAN"),
    
        mISSING("MISSING"),
    
        nULL("NULL"),
    
        nUMBER("NUMBER"),
    
        oBJECT("OBJECT"),
    
        pOJO("POJO"),
    
        sTRING("STRING");
    
    }

}

