/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param algorithm 
 * @param certificate 
 * @param kid 
 * @param providerId 
 * @param providerPriority 
 * @param publicKey 
 * @param status 
 * @param type 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class KeysMetadataRepresentationMinusKeyMetadataRepresentation (
    val algorithm: kotlin.String? = null,
    val certificate: kotlin.String? = null,
    val kid: kotlin.String? = null,
    val providerId: kotlin.String? = null,
    val providerPriority: kotlin.Long? = null,
    val publicKey: kotlin.String? = null,
    val status: kotlin.String? = null,
    val type: kotlin.String? = null
) {

}

