/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param format 
 * @param keyAlias 
 * @param keyPassword 
 * @param realmAlias 
 * @param realmCertificate 
 * @param storePassword 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class KeyStoreConfig (
    val format: kotlin.String? = null,
    val keyAlias: kotlin.String? = null,
    val keyPassword: kotlin.String? = null,
    val realmAlias: kotlin.String? = null,
    val realmCertificate: kotlin.Boolean? = null,
    val storePassword: kotlin.String? = null
) {

}

