/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param free 
 * @param freeFormated 
 * @param freePercentage 
 * @param total 
 * @param totalFormated 
 * @param used 
 * @param usedFormated 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class MemoryInfoRepresentation (
    val free: kotlin.Long? = null,
    val freeFormated: kotlin.String? = null,
    val freePercentage: kotlin.Long? = null,
    val total: kotlin.Long? = null,
    val totalFormated: kotlin.String? = null,
    val used: kotlin.Long? = null,
    val usedFormated: kotlin.String? = null
) {

}

