/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.ClientRepresentation
import fi.metatavu.keycloak.adminclient.models.GroupRepresentation
import fi.metatavu.keycloak.adminclient.models.IdentityProviderRepresentation
import fi.metatavu.keycloak.adminclient.models.RolesRepresentation
import fi.metatavu.keycloak.adminclient.models.UserRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param clients 
 * @param groups 
 * @param identityProviders 
 * @param ifResourceExists 
 * @param policy 
 * @param roles 
 * @param users 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class PartialImportRepresentation (
    val clients: kotlin.Array<ClientRepresentation>? = null,
    val groups: kotlin.Array<GroupRepresentation>? = null,
    val identityProviders: kotlin.Array<IdentityProviderRepresentation>? = null,
    val ifResourceExists: kotlin.String? = null,
    val policy: PartialImportRepresentation.Policy? = null,
    val roles: RolesRepresentation? = null,
    val users: kotlin.Array<UserRepresentation>? = null
) {

    /**
    * 
    * Values: sKIP,oVERWRITE,fAIL
    */
    enum class Policy(val value: kotlin.String){
    
        sKIP("SKIP"),
    
        oVERWRITE("OVERWRITE"),
    
        fAIL("FAIL");
    
    }

}

