/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param configType 
 * @param defaultValue 
 * @param displayName 
 * @param id 
 * @param multipleSupported 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class PasswordPolicyTypeRepresentation (
    val configType: kotlin.String? = null,
    val defaultValue: kotlin.String? = null,
    val displayName: kotlin.String? = null,
    val id: kotlin.String? = null,
    val multipleSupported: kotlin.Boolean? = null
) {

}

