/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param claims 
 * @param rsid 
 * @param rsname 
 * @param scopes 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class Permission (
    val claims: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val rsid: kotlin.String? = null,
    val rsname: kotlin.String? = null,
    val scopes: kotlin.Array<kotlin.String>? = null
) {

}

