/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.ResourceRepresentation
import fi.metatavu.keycloak.adminclient.models.ScopeRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param config 
 * @param decisionStrategy 
 * @param description 
 * @param id 
 * @param logic 
 * @param name 
 * @param owner 
 * @param policies 
 * @param resources 
 * @param resourcesData 
 * @param scopes 
 * @param scopesData 
 * @param type 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class PolicyRepresentation (
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val decisionStrategy: PolicyRepresentation.DecisionStrategy? = null,
    val description: kotlin.String? = null,
    val id: kotlin.String? = null,
    val logic: PolicyRepresentation.Logic? = null,
    val name: kotlin.String? = null,
    val owner: kotlin.String? = null,
    val policies: kotlin.Array<kotlin.String>? = null,
    val resources: kotlin.Array<kotlin.String>? = null,
    val resourcesData: kotlin.Array<ResourceRepresentation>? = null,
    val scopes: kotlin.Array<kotlin.String>? = null,
    val scopesData: kotlin.Array<ScopeRepresentation>? = null,
    val type: kotlin.String? = null
) {

    /**
    * 
    * Values: aFFIRMATIVE,uNANIMOUS,cONSENSUS
    */
    enum class DecisionStrategy(val value: kotlin.String){
    
        aFFIRMATIVE("AFFIRMATIVE"),
    
        uNANIMOUS("UNANIMOUS"),
    
        cONSENSUS("CONSENSUS");
    
    }

    /**
    * 
    * Values: pOSITIVE,nEGATIVE
    */
    enum class Logic(val value: kotlin.String){
    
        pOSITIVE("POSITIVE"),
    
        nEGATIVE("NEGATIVE");
    
    }

}

