/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.AuthenticationFlowRepresentation
import fi.metatavu.keycloak.adminclient.models.AuthenticatorConfigRepresentation
import fi.metatavu.keycloak.adminclient.models.ClientRepresentation
import fi.metatavu.keycloak.adminclient.models.ClientScopeRepresentation
import fi.metatavu.keycloak.adminclient.models.GroupRepresentation
import fi.metatavu.keycloak.adminclient.models.IdentityProviderMapperRepresentation
import fi.metatavu.keycloak.adminclient.models.IdentityProviderRepresentation
import fi.metatavu.keycloak.adminclient.models.JsonNode
import fi.metatavu.keycloak.adminclient.models.MultivaluedHashMap
import fi.metatavu.keycloak.adminclient.models.ProtocolMapperRepresentation
import fi.metatavu.keycloak.adminclient.models.RequiredActionProviderRepresentation
import fi.metatavu.keycloak.adminclient.models.RoleRepresentation
import fi.metatavu.keycloak.adminclient.models.RolesRepresentation
import fi.metatavu.keycloak.adminclient.models.ScopeMappingRepresentation
import fi.metatavu.keycloak.adminclient.models.UserFederationMapperRepresentation
import fi.metatavu.keycloak.adminclient.models.UserFederationProviderRepresentation
import fi.metatavu.keycloak.adminclient.models.UserRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param accessCodeLifespan 
 * @param accessCodeLifespanLogin 
 * @param accessCodeLifespanUserAction 
 * @param accessTokenLifespan 
 * @param accessTokenLifespanForImplicitFlow 
 * @param accountTheme 
 * @param actionTokenGeneratedByAdminLifespan 
 * @param actionTokenGeneratedByUserLifespan 
 * @param adminEventsDetailsEnabled 
 * @param adminEventsEnabled 
 * @param adminTheme 
 * @param attributes 
 * @param authenticationFlows 
 * @param authenticatorConfig 
 * @param browserFlow 
 * @param browserSecurityHeaders 
 * @param bruteForceProtected 
 * @param clientAuthenticationFlow 
 * @param clientOfflineSessionIdleTimeout 
 * @param clientOfflineSessionMaxLifespan 
 * @param clientPolicies 
 * @param clientProfiles 
 * @param clientScopeMappings 
 * @param clientScopes 
 * @param clientSessionIdleTimeout 
 * @param clientSessionMaxLifespan 
 * @param clients 
 * @param components 
 * @param defaultDefaultClientScopes 
 * @param defaultGroups 
 * @param defaultLocale 
 * @param defaultOptionalClientScopes 
 * @param defaultRole 
 * @param defaultSignatureAlgorithm 
 * @param directGrantFlow 
 * @param displayName 
 * @param displayNameHtml 
 * @param dockerAuthenticationFlow 
 * @param duplicateEmailsAllowed 
 * @param editUsernameAllowed 
 * @param emailTheme 
 * @param enabled 
 * @param enabledEventTypes 
 * @param eventsEnabled 
 * @param eventsExpiration 
 * @param eventsListeners 
 * @param failureFactor 
 * @param federatedUsers 
 * @param groups 
 * @param id 
 * @param identityProviderMappers 
 * @param identityProviders 
 * @param internationalizationEnabled 
 * @param keycloakVersion 
 * @param loginTheme 
 * @param loginWithEmailAllowed 
 * @param maxDeltaTimeSeconds 
 * @param maxFailureWaitSeconds 
 * @param minimumQuickLoginWaitSeconds 
 * @param notBefore 
 * @param oAuth2DeviceCodeLifespan 
 * @param oAuth2DevicePollingInterval 
 * @param oauth2DeviceCodeLifespan 
 * @param oauth2DevicePollingInterval 
 * @param offlineSessionIdleTimeout 
 * @param offlineSessionMaxLifespan 
 * @param offlineSessionMaxLifespanEnabled 
 * @param otpPolicyAlgorithm 
 * @param otpPolicyDigits 
 * @param otpPolicyInitialCounter 
 * @param otpPolicyLookAheadWindow 
 * @param otpPolicyPeriod 
 * @param otpPolicyType 
 * @param otpSupportedApplications 
 * @param passwordPolicy 
 * @param permanentLockout 
 * @param protocolMappers 
 * @param quickLoginCheckMilliSeconds 
 * @param realm 
 * @param refreshTokenMaxReuse 
 * @param registrationAllowed 
 * @param registrationEmailAsUsername 
 * @param registrationFlow 
 * @param rememberMe 
 * @param requiredActions 
 * @param resetCredentialsFlow 
 * @param resetPasswordAllowed 
 * @param revokeRefreshToken 
 * @param roles 
 * @param scopeMappings 
 * @param smtpServer 
 * @param sslRequired 
 * @param ssoSessionIdleTimeout 
 * @param ssoSessionIdleTimeoutRememberMe 
 * @param ssoSessionMaxLifespan 
 * @param ssoSessionMaxLifespanRememberMe 
 * @param supportedLocales 
 * @param userFederationMappers 
 * @param userFederationProviders 
 * @param userManagedAccessAllowed 
 * @param users 
 * @param verifyEmail 
 * @param waitIncrementSeconds 
 * @param webAuthnPolicyAcceptableAaguids 
 * @param webAuthnPolicyAttestationConveyancePreference 
 * @param webAuthnPolicyAuthenticatorAttachment 
 * @param webAuthnPolicyAvoidSameAuthenticatorRegister 
 * @param webAuthnPolicyCreateTimeout 
 * @param webAuthnPolicyPasswordlessAcceptableAaguids 
 * @param webAuthnPolicyPasswordlessAttestationConveyancePreference 
 * @param webAuthnPolicyPasswordlessAuthenticatorAttachment 
 * @param webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister 
 * @param webAuthnPolicyPasswordlessCreateTimeout 
 * @param webAuthnPolicyPasswordlessRequireResidentKey 
 * @param webAuthnPolicyPasswordlessRpEntityName 
 * @param webAuthnPolicyPasswordlessRpId 
 * @param webAuthnPolicyPasswordlessSignatureAlgorithms 
 * @param webAuthnPolicyPasswordlessUserVerificationRequirement 
 * @param webAuthnPolicyRequireResidentKey 
 * @param webAuthnPolicyRpEntityName 
 * @param webAuthnPolicyRpId 
 * @param webAuthnPolicySignatureAlgorithms 
 * @param webAuthnPolicyUserVerificationRequirement 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class RealmRepresentation (
    val accessCodeLifespan: kotlin.Int? = null,
    val accessCodeLifespanLogin: kotlin.Int? = null,
    val accessCodeLifespanUserAction: kotlin.Int? = null,
    val accessTokenLifespan: kotlin.Int? = null,
    val accessTokenLifespanForImplicitFlow: kotlin.Int? = null,
    val accountTheme: kotlin.String? = null,
    val actionTokenGeneratedByAdminLifespan: kotlin.Int? = null,
    val actionTokenGeneratedByUserLifespan: kotlin.Int? = null,
    val adminEventsDetailsEnabled: kotlin.Boolean? = null,
    val adminEventsEnabled: kotlin.Boolean? = null,
    val adminTheme: kotlin.String? = null,
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val authenticationFlows: kotlin.Array<AuthenticationFlowRepresentation>? = null,
    val authenticatorConfig: kotlin.Array<AuthenticatorConfigRepresentation>? = null,
    val browserFlow: kotlin.String? = null,
    val browserSecurityHeaders: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val bruteForceProtected: kotlin.Boolean? = null,
    val clientAuthenticationFlow: kotlin.String? = null,
    val clientOfflineSessionIdleTimeout: kotlin.Int? = null,
    val clientOfflineSessionMaxLifespan: kotlin.Int? = null,
    val clientPolicies: JsonNode? = null,
    val clientProfiles: JsonNode? = null,
    val clientScopeMappings: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val clientScopes: kotlin.Array<ClientScopeRepresentation>? = null,
    val clientSessionIdleTimeout: kotlin.Int? = null,
    val clientSessionMaxLifespan: kotlin.Int? = null,
    val clients: kotlin.Array<ClientRepresentation>? = null,
    val components: MultivaluedHashMap? = null,
    val defaultDefaultClientScopes: kotlin.Array<kotlin.String>? = null,
    val defaultGroups: kotlin.Array<kotlin.String>? = null,
    val defaultLocale: kotlin.String? = null,
    val defaultOptionalClientScopes: kotlin.Array<kotlin.String>? = null,
    val defaultRole: RoleRepresentation? = null,
    val defaultSignatureAlgorithm: kotlin.String? = null,
    val directGrantFlow: kotlin.String? = null,
    val displayName: kotlin.String? = null,
    val displayNameHtml: kotlin.String? = null,
    val dockerAuthenticationFlow: kotlin.String? = null,
    val duplicateEmailsAllowed: kotlin.Boolean? = null,
    val editUsernameAllowed: kotlin.Boolean? = null,
    val emailTheme: kotlin.String? = null,
    val enabled: kotlin.Boolean? = null,
    val enabledEventTypes: kotlin.Array<kotlin.String>? = null,
    val eventsEnabled: kotlin.Boolean? = null,
    val eventsExpiration: kotlin.Long? = null,
    val eventsListeners: kotlin.Array<kotlin.String>? = null,
    val failureFactor: kotlin.Int? = null,
    val federatedUsers: kotlin.Array<UserRepresentation>? = null,
    val groups: kotlin.Array<GroupRepresentation>? = null,
    val id: kotlin.String? = null,
    val identityProviderMappers: kotlin.Array<IdentityProviderMapperRepresentation>? = null,
    val identityProviders: kotlin.Array<IdentityProviderRepresentation>? = null,
    val internationalizationEnabled: kotlin.Boolean? = null,
    val keycloakVersion: kotlin.String? = null,
    val loginTheme: kotlin.String? = null,
    val loginWithEmailAllowed: kotlin.Boolean? = null,
    val maxDeltaTimeSeconds: kotlin.Int? = null,
    val maxFailureWaitSeconds: kotlin.Int? = null,
    val minimumQuickLoginWaitSeconds: kotlin.Int? = null,
    val notBefore: kotlin.Int? = null,
    val oAuth2DeviceCodeLifespan: kotlin.Int? = null,
    val oAuth2DevicePollingInterval: kotlin.Int? = null,
    val oauth2DeviceCodeLifespan: kotlin.Int? = null,
    val oauth2DevicePollingInterval: kotlin.Int? = null,
    val offlineSessionIdleTimeout: kotlin.Int? = null,
    val offlineSessionMaxLifespan: kotlin.Int? = null,
    val offlineSessionMaxLifespanEnabled: kotlin.Boolean? = null,
    val otpPolicyAlgorithm: kotlin.String? = null,
    val otpPolicyDigits: kotlin.Int? = null,
    val otpPolicyInitialCounter: kotlin.Int? = null,
    val otpPolicyLookAheadWindow: kotlin.Int? = null,
    val otpPolicyPeriod: kotlin.Int? = null,
    val otpPolicyType: kotlin.String? = null,
    val otpSupportedApplications: kotlin.Array<kotlin.String>? = null,
    val passwordPolicy: kotlin.String? = null,
    val permanentLockout: kotlin.Boolean? = null,
    val protocolMappers: kotlin.Array<ProtocolMapperRepresentation>? = null,
    val quickLoginCheckMilliSeconds: kotlin.Long? = null,
    val realm: kotlin.String? = null,
    val refreshTokenMaxReuse: kotlin.Int? = null,
    val registrationAllowed: kotlin.Boolean? = null,
    val registrationEmailAsUsername: kotlin.Boolean? = null,
    val registrationFlow: kotlin.String? = null,
    val rememberMe: kotlin.Boolean? = null,
    val requiredActions: kotlin.Array<RequiredActionProviderRepresentation>? = null,
    val resetCredentialsFlow: kotlin.String? = null,
    val resetPasswordAllowed: kotlin.Boolean? = null,
    val revokeRefreshToken: kotlin.Boolean? = null,
    val roles: RolesRepresentation? = null,
    val scopeMappings: kotlin.Array<ScopeMappingRepresentation>? = null,
    val smtpServer: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val sslRequired: kotlin.String? = null,
    val ssoSessionIdleTimeout: kotlin.Int? = null,
    val ssoSessionIdleTimeoutRememberMe: kotlin.Int? = null,
    val ssoSessionMaxLifespan: kotlin.Int? = null,
    val ssoSessionMaxLifespanRememberMe: kotlin.Int? = null,
    val supportedLocales: kotlin.Array<kotlin.String>? = null,
    val userFederationMappers: kotlin.Array<UserFederationMapperRepresentation>? = null,
    val userFederationProviders: kotlin.Array<UserFederationProviderRepresentation>? = null,
    val userManagedAccessAllowed: kotlin.Boolean? = null,
    val users: kotlin.Array<UserRepresentation>? = null,
    val verifyEmail: kotlin.Boolean? = null,
    val waitIncrementSeconds: kotlin.Int? = null,
    val webAuthnPolicyAcceptableAaguids: kotlin.Array<kotlin.String>? = null,
    val webAuthnPolicyAttestationConveyancePreference: kotlin.String? = null,
    val webAuthnPolicyAuthenticatorAttachment: kotlin.String? = null,
    val webAuthnPolicyAvoidSameAuthenticatorRegister: kotlin.Boolean? = null,
    val webAuthnPolicyCreateTimeout: kotlin.Int? = null,
    val webAuthnPolicyPasswordlessAcceptableAaguids: kotlin.Array<kotlin.String>? = null,
    val webAuthnPolicyPasswordlessAttestationConveyancePreference: kotlin.String? = null,
    val webAuthnPolicyPasswordlessAuthenticatorAttachment: kotlin.String? = null,
    val webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister: kotlin.Boolean? = null,
    val webAuthnPolicyPasswordlessCreateTimeout: kotlin.Int? = null,
    val webAuthnPolicyPasswordlessRequireResidentKey: kotlin.String? = null,
    val webAuthnPolicyPasswordlessRpEntityName: kotlin.String? = null,
    val webAuthnPolicyPasswordlessRpId: kotlin.String? = null,
    val webAuthnPolicyPasswordlessSignatureAlgorithms: kotlin.Array<kotlin.String>? = null,
    val webAuthnPolicyPasswordlessUserVerificationRequirement: kotlin.String? = null,
    val webAuthnPolicyRequireResidentKey: kotlin.String? = null,
    val webAuthnPolicyRpEntityName: kotlin.String? = null,
    val webAuthnPolicyRpId: kotlin.String? = null,
    val webAuthnPolicySignatureAlgorithms: kotlin.Array<kotlin.String>? = null,
    val webAuthnPolicyUserVerificationRequirement: kotlin.String? = null
) {

}

