/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param adminEventsDetailsEnabled 
 * @param adminEventsEnabled 
 * @param enabledEventTypes 
 * @param eventsEnabled 
 * @param eventsExpiration 
 * @param eventsListeners 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class RealmEventsConfigRepresentation (
    val adminEventsDetailsEnabled: kotlin.Boolean? = null,
    val adminEventsEnabled: kotlin.Boolean? = null,
    val enabledEventTypes: kotlin.Array<kotlin.String>? = null,
    val eventsEnabled: kotlin.Boolean? = null,
    val eventsExpiration: kotlin.Long? = null,
    val eventsListeners: kotlin.Array<kotlin.String>? = null
) {

}

