/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param alias 
 * @param config 
 * @param defaultAction 
 * @param enabled 
 * @param name 
 * @param priority 
 * @param providerId 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class RequiredActionProviderRepresentation (
    val alias: kotlin.String? = null,
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val defaultAction: kotlin.Boolean? = null,
    val enabled: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val priority: kotlin.Int? = null,
    val providerId: kotlin.String? = null
) {

}

