/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param added 
 * @param failed 
 * @param ignored 
 * @param removed 
 * @param status 
 * @param updated 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class SynchronizationResult (
    val added: kotlin.Int? = null,
    val failed: kotlin.Int? = null,
    val ignored: kotlin.Boolean? = null,
    val removed: kotlin.Int? = null,
    val status: kotlin.String? = null,
    val updated: kotlin.Int? = null
) {

}

