/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param fileEncoding 
 * @param javaHome 
 * @param javaRuntime 
 * @param javaVendor 
 * @param javaVersion 
 * @param javaVm 
 * @param javaVmVersion 
 * @param osArchitecture 
 * @param osName 
 * @param osVersion 
 * @param serverTime 
 * @param uptime 
 * @param uptimeMillis 
 * @param userDir 
 * @param userLocale 
 * @param userName 
 * @param userTimezone 
 * @param version 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class SystemInfoRepresentation (
    val fileEncoding: kotlin.String? = null,
    val javaHome: kotlin.String? = null,
    val javaRuntime: kotlin.String? = null,
    val javaVendor: kotlin.String? = null,
    val javaVersion: kotlin.String? = null,
    val javaVm: kotlin.String? = null,
    val javaVmVersion: kotlin.String? = null,
    val osArchitecture: kotlin.String? = null,
    val osName: kotlin.String? = null,
    val osVersion: kotlin.String? = null,
    val serverTime: kotlin.String? = null,
    val uptime: kotlin.String? = null,
    val uptimeMillis: kotlin.Long? = null,
    val userDir: kotlin.String? = null,
    val userLocale: kotlin.String? = null,
    val userName: kotlin.String? = null,
    val userTimezone: kotlin.String? = null,
    val version: kotlin.String? = null
) {

}

