/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param action 
 * @param authType 
 * @param bindCredential 
 * @param bindDn 
 * @param componentId 
 * @param connectionTimeout 
 * @param connectionUrl 
 * @param startTls 
 * @param useTruststoreSpi 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class TestLdapConnectionRepresentation (
    val action: kotlin.String? = null,
    val authType: kotlin.String? = null,
    val bindCredential: kotlin.String? = null,
    val bindDn: kotlin.String? = null,
    val componentId: kotlin.String? = null,
    val connectionTimeout: kotlin.String? = null,
    val connectionUrl: kotlin.String? = null,
    val startTls: kotlin.String? = null,
    val useTruststoreSpi: kotlin.String? = null
) {

}

