/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param clientId 
 * @param createdDate 
 * @param grantedClientScopes 
 * @param lastUpdatedDate 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class UserConsentRepresentation (
    val clientId: kotlin.String? = null,
    val createdDate: kotlin.Long? = null,
    val grantedClientScopes: kotlin.Array<kotlin.String>? = null,
    val lastUpdatedDate: kotlin.Long? = null
) {

}

