/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models


        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param changedSyncPeriod 
 * @param config 
 * @param displayName 
 * @param fullSyncPeriod 
 * @param id 
 * @param lastSync 
 * @param priority 
 * @param providerName 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class UserFederationProviderRepresentation (
    val changedSyncPeriod: kotlin.Int? = null,
    val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val displayName: kotlin.String? = null,
    val fullSyncPeriod: kotlin.Int? = null,
    val id: kotlin.String? = null,
    val lastSync: kotlin.Int? = null,
    val priority: kotlin.Int? = null,
    val providerName: kotlin.String? = null
) {

}

