/**
* Keycloak Admin REST API
* This is a REST API reference for the Keycloak Admin
*
* The version of the OpenAPI document: 1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package fi.metatavu.keycloak.adminclient.models

import fi.metatavu.keycloak.adminclient.models.CredentialRepresentation
import fi.metatavu.keycloak.adminclient.models.FederatedIdentityRepresentation
import fi.metatavu.keycloak.adminclient.models.UserConsentRepresentation

        
import com.google.gson.annotations.SerializedName
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
/**
 * 
 * @param access 
 * @param attributes 
 * @param clientConsents 
 * @param clientRoles 
 * @param createdTimestamp 
 * @param credentials 
 * @param disableableCredentialTypes 
 * @param email 
 * @param emailVerified 
 * @param enabled 
 * @param federatedIdentities 
 * @param federationLink 
 * @param firstName 
 * @param groups 
 * @param id 
 * @param lastName 
 * @param notBefore 
 * @param origin 
 * @param realmRoles 
 * @param requiredActions 
 * @param self 
 * @param serviceAccountClientId 
 * @param username 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
data class UserRepresentation (
    val access: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val clientConsents: kotlin.Array<UserConsentRepresentation>? = null,
    val clientRoles: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,
    val createdTimestamp: kotlin.Long? = null,
    val credentials: kotlin.Array<CredentialRepresentation>? = null,
    val disableableCredentialTypes: kotlin.Array<kotlin.String>? = null,
    val email: kotlin.String? = null,
    val emailVerified: kotlin.Boolean? = null,
    val enabled: kotlin.Boolean? = null,
    val federatedIdentities: kotlin.Array<FederatedIdentityRepresentation>? = null,
    val federationLink: kotlin.String? = null,
    val firstName: kotlin.String? = null,
    val groups: kotlin.Array<kotlin.String>? = null,
    val id: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val notBefore: kotlin.Int? = null,
    val origin: kotlin.String? = null,
    val realmRoles: kotlin.Array<kotlin.String>? = null,
    val requiredActions: kotlin.Array<kotlin.String>? = null,
    val self: kotlin.String? = null,
    val serviceAccountClientId: kotlin.String? = null,
    val username: kotlin.String? = null
) {

}

